### ISSUE TITLE
Error show

### ISSUE THREAD

**Issue by Cryogenus** [lee-lindley/PdfGen#3]
![image](https://user-images.githubusercontent.com/41005883/147336183-b2101a4e-1220-4b98-8e9d-3fd7ce1cb309.png)

**Comment by Cryogenus** [comment]
Oracle version - Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

**Comment by lee-lindley** [comment]
This error is in as_pdf3 which I'm just providing a copy of. This looks like 3 separate error messages all having to do with your font and/or character set. What you have provided is in not enough to figure it out and I don't think I want to try anyway.  I would suggest looking into the characters set you are using by default in your database and then the font you are trying to use here.
